### ISSUE TITLE
Tuple validation

### ISSUE THREAD

**Issue by masaeedu** [typeable/schematic#12]
Thank you for a very useful library. I was wondering if it possible in schematic to represent schemas for heterogeneous lists (e.g. `["foo", 42]`)? The corresponding JSON schema would be `{ type: "array", items: [{ type: string }, { type: number }] }`.

I looked around in `Schema.hs` and couldn't see any such thing, but thought I'd check anyway.

**Comment by dredozubov** [comment]
@masaeedu It's currently not supported by schematic. It's possible to do, but I haven't really seen the need for it, because the same data can be easily represented as an JSON object like `{ "a": "foo", "b": 42}` without adding complexity from the haskell side of things.

**Comment by masaeedu** [comment]
@dredozubov That's reasonable. Thanks.
